spring:
  config:
    activate:
      on-profile: "prod"

build:spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Pelican Sudhir - Product Owner"
    email: "pelican@eazybank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards related prod APIs "
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "sandra@eazybank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721